language: objective-c
osx_image: xcode12.2

cache:
  directories:
  - Carthage

before_script:
    - travis_wait 30 ./bin/carthage bootstrap --use-xcframeworks --cache-builds

script:
    # Build frameworks and run tests
    - xcodebuild -project NightscoutService.xcodeproj -scheme Shared build -destination name="iPhone 8" test 

